title: Jekyll ZIP Release Showcase
tagline: Example how to build and release Jekyll site to ZIP release
author.name: Sergey Trasko
author.url: https://github.com/sergeytrasko
google_analytics:
theme: monophase
plugins:
  - jekyll-relative-links